name: carhub
description: "CarHub Mobile App"
publish_to: 'none'
version: 1.2.2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.0.10+1
  super_rich_text: ^1.0.0
  awesome_extensions: ^2.0.13
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  collection: ^1.18.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.4
  flutter_debouncer: ^2.0.0
  flutter_easyloading: ^3.0.5
  go_router: ^14.2.9
  freezed_result: ^1.0.3+1
  image_picker: ^1.0.7
  flutter_flavorizr: ^2.2.3
  adaptive_theme: ^3.6.0
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  otp_pin_field: ^1.2.2
  #  country_picker: ^2.0.25
  auto_size_text: ^3.0.0
  flutter_switch: ^0.3.2
  calendar_date_picker2: ^0.5.5
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  http: ^1.2.1
  k_chart_plus:
    #    path: ../k_chart_plus_fork
    git:
      url: https://github.com/tnvinh2711/k_chart_plus
      ref: dev #branch name
  mobkit_dashed_border: ^0.0.6
  json_annotation: ^4.8.1
  local_auth: ^2.2.0
  expandable_page_view: ^1.0.17
  mobile_scanner: ^5.1.1
  flutter_inappwebview: ^6.1.1
  badges: ^3.1.2
  timelines: ^0.1.0
  chopper: ^8.0.2
  connectivity_plus: ^6.1.0
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.2.2
  device_info_plus: ^10.1.2
  easy_load_more: ^1.1.0
  image_gallery_saver: ^2.0.3
  cached_network_image: ^3.4.1
  chucker_flutter: ^1.8.1
  client_information: ^2.1.4
  hyperkyc_flutter: ^0.30.1
  uuid: ^4.5.1
  pusher_channels_flutter: ^2.2.1
  sentry_flutter: ^8.9.0
#  diamond_node_slider: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.7.0
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.2
  chopper_generator: ^8.0.2
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  go_router_builder: any
  build_verify: any

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - shorebird.yaml


  fonts:
    - family: HindMaduraiLight
      fonts:
        - asset: assets/fonts/HindMadurai-Light.ttf
    - family: HindMaduraiMedium
      fonts:
        - asset: assets/fonts/HindMadurai-Medium.ttf
    - family: HindMaduraiRegular
      fonts:
        - asset: assets/fonts/HindMadurai-Regular.ttf
    - family: HindMaduraiSemiBold
      fonts:
        - asset: assets/fonts/HindMadurai-SemiBold.ttf
    - family: HindMaduraiBold
      fonts:
        - asset: assets/fonts/HindMadurai-Bold.ttf

flutter_intl:
  enabled: true

flutter_gen:
  integrations:
    flutter_svg: true

export:
  - lib/

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.gr.dart"
  - "**/_*.dart"
  - "main_development.dart"
  - "main_staging.dart"
  - "main_production.dart"
  - "gen/**"
  - "generated/**"
  - "l10n/**"


